GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTcwMDIzNTEsImV4cCI6MTY1NzAwMjM3MSwiYXVkIjoiNjJjMzE2NTM5ZmE3NjgyMGVhZmY5ZDEyIiwiaXNzIjoibW9oYW1tYWRob3NzZWluLmNvbSJ9.fuFDcDoyKs-Jk5tqLZtv-H9AlNq33R4tfjF8Gxny1NM

### Login route
POST  http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "johndoe@gmail.com",
    "password": "mha77794060"
}

### Register route
POST  http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "johne777@gmail.com",
    "password": "mha77794060"
}

### Refresh token route
POST  http://localhost:3000/auth/refresh-token

### Logout route
DELETE   http://localhost:3000/auth/logout